workspace = { members = ["json_parser_macro"] }

[package]
name = "json-parser"
version = "0.1.0"
edition = "2021"

[lints.clippy]
never_loop = "allow"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json_parser_macro = { path = "./json_parser_macro" }
