workspace = { members = ["jsode_macro"] }

[package]
name = "jsode"
version = "0.1.0"
edition = "2021"
description = "a simple, zero-dependency json parser"
license = "MIT"
repository = "https://github.com/taminhtienhai/jsode"
documentation = "https://docs.rs/jsode"

[lints.clippy]
never_loop = "allow"

[dependencies]
jsode_macro = { version = "0.1" }

[features]
default = ["macro"]
macro = []
unstable = [] # introduce memory leak at the moment