workspace = { members = ["jsode_macro"] }

[package]
name = "jsode"
version = "0.1.0"
edition = "2021"

[lints.clippy]
never_loop = "allow"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsode_macro = { path = "./jsode_macro" }
